// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: offers_proto.proto

package griffib.shopdroid.comms;

public final class OffersProto {
  private OffersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Offer extends
      com.google.protobuf.GeneratedMessage {
    // Use Offer.newBuilder() to construct.
    private Offer() {
      initFields();
    }
    private Offer(boolean noInit) {}
    
    private static final Offer defaultInstance;
    public static Offer getDefaultInstance() {
      return defaultInstance;
    }
    
    public Offer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return griffib.shopdroid.comms.OffersProto.internal_static_griffib_shopdroid_comms_Offer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return griffib.shopdroid.comms.OffersProto.internal_static_griffib_shopdroid_comms_Offer_fieldAccessorTable;
    }
    
    public static final class Attribute extends
        com.google.protobuf.GeneratedMessage {
      // Use Attribute.newBuilder() to construct.
      private Attribute() {
        initFields();
      }
      private Attribute(boolean noInit) {}
      
      private static final Attribute defaultInstance;
      public static Attribute getDefaultInstance() {
        return defaultInstance;
      }
      
      public Attribute getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return griffib.shopdroid.comms.OffersProto.internal_static_griffib_shopdroid_comms_Offer_Attribute_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return griffib.shopdroid.comms.OffersProto.internal_static_griffib_shopdroid_comms_Offer_Attribute_fieldAccessorTable;
      }
      
      // optional string predicate = 1;
      public static final int PREDICATE_FIELD_NUMBER = 1;
      private boolean hasPredicate;
      private java.lang.String predicate_ = "";
      public boolean hasPredicate() { return hasPredicate; }
      public java.lang.String getPredicate() { return predicate_; }
      
      // optional string value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private boolean hasValue;
      private java.lang.String value_ = "";
      public boolean hasValue() { return hasValue; }
      public java.lang.String getValue() { return value_; }
      
      private void initFields() {
      }
      public final boolean isInitialized() {
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (hasPredicate()) {
          output.writeString(1, getPredicate());
        }
        if (hasValue()) {
          output.writeString(2, getValue());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (hasPredicate()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getPredicate());
        }
        if (hasValue()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getValue());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static griffib.shopdroid.comms.OffersProto.Offer.Attribute parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(griffib.shopdroid.comms.OffersProto.Offer.Attribute prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> {
        private griffib.shopdroid.comms.OffersProto.Offer.Attribute result;
        
        // Construct using griffib.shopdroid.comms.OffersProto.Offer.Attribute.newBuilder()
        private Builder() {}
        
        private static Builder create() {
          Builder builder = new Builder();
          builder.result = new griffib.shopdroid.comms.OffersProto.Offer.Attribute();
          return builder;
        }
        
        protected griffib.shopdroid.comms.OffersProto.Offer.Attribute internalGetResult() {
          return result;
        }
        
        public Builder clear() {
          if (result == null) {
            throw new IllegalStateException(
              "Cannot call clear() after build().");
          }
          result = new griffib.shopdroid.comms.OffersProto.Offer.Attribute();
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(result);
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return griffib.shopdroid.comms.OffersProto.Offer.Attribute.getDescriptor();
        }
        
        public griffib.shopdroid.comms.OffersProto.Offer.Attribute getDefaultInstanceForType() {
          return griffib.shopdroid.comms.OffersProto.Offer.Attribute.getDefaultInstance();
        }
        
        public boolean isInitialized() {
          return result.isInitialized();
        }
        public griffib.shopdroid.comms.OffersProto.Offer.Attribute build() {
          if (result != null && !isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return buildPartial();
        }
        
        private griffib.shopdroid.comms.OffersProto.Offer.Attribute buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          if (!isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return buildPartial();
        }
        
        public griffib.shopdroid.comms.OffersProto.Offer.Attribute buildPartial() {
          if (result == null) {
            throw new IllegalStateException(
              "build() has already been called on this Builder.");
          }
          griffib.shopdroid.comms.OffersProto.Offer.Attribute returnMe = result;
          result = null;
          return returnMe;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof griffib.shopdroid.comms.OffersProto.Offer.Attribute) {
            return mergeFrom((griffib.shopdroid.comms.OffersProto.Offer.Attribute)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(griffib.shopdroid.comms.OffersProto.Offer.Attribute other) {
          if (other == griffib.shopdroid.comms.OffersProto.Offer.Attribute.getDefaultInstance()) return this;
          if (other.hasPredicate()) {
            setPredicate(other.getPredicate());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  return this;
                }
                break;
              }
              case 10: {
                setPredicate(input.readString());
                break;
              }
              case 18: {
                setValue(input.readString());
                break;
              }
            }
          }
        }
        
        
        // optional string predicate = 1;
        public boolean hasPredicate() {
          return result.hasPredicate();
        }
        public java.lang.String getPredicate() {
          return result.getPredicate();
        }
        public Builder setPredicate(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasPredicate = true;
          result.predicate_ = value;
          return this;
        }
        public Builder clearPredicate() {
          result.hasPredicate = false;
          result.predicate_ = getDefaultInstance().getPredicate();
          return this;
        }
        
        // optional string value = 2;
        public boolean hasValue() {
          return result.hasValue();
        }
        public java.lang.String getValue() {
          return result.getValue();
        }
        public Builder setValue(java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  result.hasValue = true;
          result.value_ = value;
          return this;
        }
        public Builder clearValue() {
          result.hasValue = false;
          result.value_ = getDefaultInstance().getValue();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:griffib.shopdroid.comms.Offer.Attribute)
      }
      
      static {
        defaultInstance = new Attribute(true);
        griffib.shopdroid.comms.OffersProto.internalForceInit();
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:griffib.shopdroid.comms.Offer.Attribute)
    }
    
    // optional string product = 1;
    public static final int PRODUCT_FIELD_NUMBER = 1;
    private boolean hasProduct;
    private java.lang.String product_ = "";
    public boolean hasProduct() { return hasProduct; }
    public java.lang.String getProduct() { return product_; }
    
    // optional string offer_sum = 2;
    public static final int OFFER_SUM_FIELD_NUMBER = 2;
    private boolean hasOfferSum;
    private java.lang.String offerSum_ = "";
    public boolean hasOfferSum() { return hasOfferSum; }
    public java.lang.String getOfferSum() { return offerSum_; }
    
    // repeated .griffib.shopdroid.comms.Offer.Attribute attribute = 3;
    public static final int ATTRIBUTE_FIELD_NUMBER = 3;
    private java.util.List<griffib.shopdroid.comms.OffersProto.Offer.Attribute> attribute_ =
      java.util.Collections.emptyList();
    public java.util.List<griffib.shopdroid.comms.OffersProto.Offer.Attribute> getAttributeList() {
      return attribute_;
    }
    public int getAttributeCount() { return attribute_.size(); }
    public griffib.shopdroid.comms.OffersProto.Offer.Attribute getAttribute(int index) {
      return attribute_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProduct()) {
        output.writeString(1, getProduct());
      }
      if (hasOfferSum()) {
        output.writeString(2, getOfferSum());
      }
      for (griffib.shopdroid.comms.OffersProto.Offer.Attribute element : getAttributeList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProduct()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getProduct());
      }
      if (hasOfferSum()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getOfferSum());
      }
      for (griffib.shopdroid.comms.OffersProto.Offer.Attribute element : getAttributeList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(griffib.shopdroid.comms.OffersProto.Offer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private griffib.shopdroid.comms.OffersProto.Offer result;
      
      // Construct using griffib.shopdroid.comms.OffersProto.Offer.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new griffib.shopdroid.comms.OffersProto.Offer();
        return builder;
      }
      
      protected griffib.shopdroid.comms.OffersProto.Offer internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new griffib.shopdroid.comms.OffersProto.Offer();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return griffib.shopdroid.comms.OffersProto.Offer.getDescriptor();
      }
      
      public griffib.shopdroid.comms.OffersProto.Offer getDefaultInstanceForType() {
        return griffib.shopdroid.comms.OffersProto.Offer.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public griffib.shopdroid.comms.OffersProto.Offer build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private griffib.shopdroid.comms.OffersProto.Offer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public griffib.shopdroid.comms.OffersProto.Offer buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.attribute_ != java.util.Collections.EMPTY_LIST) {
          result.attribute_ =
            java.util.Collections.unmodifiableList(result.attribute_);
        }
        griffib.shopdroid.comms.OffersProto.Offer returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof griffib.shopdroid.comms.OffersProto.Offer) {
          return mergeFrom((griffib.shopdroid.comms.OffersProto.Offer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(griffib.shopdroid.comms.OffersProto.Offer other) {
        if (other == griffib.shopdroid.comms.OffersProto.Offer.getDefaultInstance()) return this;
        if (other.hasProduct()) {
          setProduct(other.getProduct());
        }
        if (other.hasOfferSum()) {
          setOfferSum(other.getOfferSum());
        }
        if (!other.attribute_.isEmpty()) {
          if (result.attribute_.isEmpty()) {
            result.attribute_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer.Attribute>();
          }
          result.attribute_.addAll(other.attribute_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setProduct(input.readString());
              break;
            }
            case 18: {
              setOfferSum(input.readString());
              break;
            }
            case 26: {
              griffib.shopdroid.comms.OffersProto.Offer.Attribute.Builder subBuilder = griffib.shopdroid.comms.OffersProto.Offer.Attribute.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAttribute(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional string product = 1;
      public boolean hasProduct() {
        return result.hasProduct();
      }
      public java.lang.String getProduct() {
        return result.getProduct();
      }
      public Builder setProduct(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProduct = true;
        result.product_ = value;
        return this;
      }
      public Builder clearProduct() {
        result.hasProduct = false;
        result.product_ = getDefaultInstance().getProduct();
        return this;
      }
      
      // optional string offer_sum = 2;
      public boolean hasOfferSum() {
        return result.hasOfferSum();
      }
      public java.lang.String getOfferSum() {
        return result.getOfferSum();
      }
      public Builder setOfferSum(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOfferSum = true;
        result.offerSum_ = value;
        return this;
      }
      public Builder clearOfferSum() {
        result.hasOfferSum = false;
        result.offerSum_ = getDefaultInstance().getOfferSum();
        return this;
      }
      
      // repeated .griffib.shopdroid.comms.Offer.Attribute attribute = 3;
      public java.util.List<griffib.shopdroid.comms.OffersProto.Offer.Attribute> getAttributeList() {
        return java.util.Collections.unmodifiableList(result.attribute_);
      }
      public int getAttributeCount() {
        return result.getAttributeCount();
      }
      public griffib.shopdroid.comms.OffersProto.Offer.Attribute getAttribute(int index) {
        return result.getAttribute(index);
      }
      public Builder setAttribute(int index, griffib.shopdroid.comms.OffersProto.Offer.Attribute value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.attribute_.set(index, value);
        return this;
      }
      public Builder setAttribute(int index, griffib.shopdroid.comms.OffersProto.Offer.Attribute.Builder builderForValue) {
        result.attribute_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAttribute(griffib.shopdroid.comms.OffersProto.Offer.Attribute value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.attribute_.isEmpty()) {
          result.attribute_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer.Attribute>();
        }
        result.attribute_.add(value);
        return this;
      }
      public Builder addAttribute(griffib.shopdroid.comms.OffersProto.Offer.Attribute.Builder builderForValue) {
        if (result.attribute_.isEmpty()) {
          result.attribute_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer.Attribute>();
        }
        result.attribute_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAttribute(
          java.lang.Iterable<? extends griffib.shopdroid.comms.OffersProto.Offer.Attribute> values) {
        if (result.attribute_.isEmpty()) {
          result.attribute_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer.Attribute>();
        }
        super.addAll(values, result.attribute_);
        return this;
      }
      public Builder clearAttribute() {
        result.attribute_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:griffib.shopdroid.comms.Offer)
    }
    
    static {
      defaultInstance = new Offer(true);
      griffib.shopdroid.comms.OffersProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:griffib.shopdroid.comms.Offer)
  }
  
  public static final class Offers extends
      com.google.protobuf.GeneratedMessage {
    // Use Offers.newBuilder() to construct.
    private Offers() {
      initFields();
    }
    private Offers(boolean noInit) {}
    
    private static final Offers defaultInstance;
    public static Offers getDefaultInstance() {
      return defaultInstance;
    }
    
    public Offers getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return griffib.shopdroid.comms.OffersProto.internal_static_griffib_shopdroid_comms_Offers_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return griffib.shopdroid.comms.OffersProto.internal_static_griffib_shopdroid_comms_Offers_fieldAccessorTable;
    }
    
    // repeated .griffib.shopdroid.comms.Offer offer = 1;
    public static final int OFFER_FIELD_NUMBER = 1;
    private java.util.List<griffib.shopdroid.comms.OffersProto.Offer> offer_ =
      java.util.Collections.emptyList();
    public java.util.List<griffib.shopdroid.comms.OffersProto.Offer> getOfferList() {
      return offer_;
    }
    public int getOfferCount() { return offer_.size(); }
    public griffib.shopdroid.comms.OffersProto.Offer getOffer(int index) {
      return offer_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (griffib.shopdroid.comms.OffersProto.Offer element : getOfferList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (griffib.shopdroid.comms.OffersProto.Offer element : getOfferList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static griffib.shopdroid.comms.OffersProto.Offers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(griffib.shopdroid.comms.OffersProto.Offers prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private griffib.shopdroid.comms.OffersProto.Offers result;
      
      // Construct using griffib.shopdroid.comms.OffersProto.Offers.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new griffib.shopdroid.comms.OffersProto.Offers();
        return builder;
      }
      
      protected griffib.shopdroid.comms.OffersProto.Offers internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new griffib.shopdroid.comms.OffersProto.Offers();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return griffib.shopdroid.comms.OffersProto.Offers.getDescriptor();
      }
      
      public griffib.shopdroid.comms.OffersProto.Offers getDefaultInstanceForType() {
        return griffib.shopdroid.comms.OffersProto.Offers.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public griffib.shopdroid.comms.OffersProto.Offers build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private griffib.shopdroid.comms.OffersProto.Offers buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public griffib.shopdroid.comms.OffersProto.Offers buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.offer_ != java.util.Collections.EMPTY_LIST) {
          result.offer_ =
            java.util.Collections.unmodifiableList(result.offer_);
        }
        griffib.shopdroid.comms.OffersProto.Offers returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof griffib.shopdroid.comms.OffersProto.Offers) {
          return mergeFrom((griffib.shopdroid.comms.OffersProto.Offers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(griffib.shopdroid.comms.OffersProto.Offers other) {
        if (other == griffib.shopdroid.comms.OffersProto.Offers.getDefaultInstance()) return this;
        if (!other.offer_.isEmpty()) {
          if (result.offer_.isEmpty()) {
            result.offer_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer>();
          }
          result.offer_.addAll(other.offer_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              griffib.shopdroid.comms.OffersProto.Offer.Builder subBuilder = griffib.shopdroid.comms.OffersProto.Offer.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOffer(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .griffib.shopdroid.comms.Offer offer = 1;
      public java.util.List<griffib.shopdroid.comms.OffersProto.Offer> getOfferList() {
        return java.util.Collections.unmodifiableList(result.offer_);
      }
      public int getOfferCount() {
        return result.getOfferCount();
      }
      public griffib.shopdroid.comms.OffersProto.Offer getOffer(int index) {
        return result.getOffer(index);
      }
      public Builder setOffer(int index, griffib.shopdroid.comms.OffersProto.Offer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.offer_.set(index, value);
        return this;
      }
      public Builder setOffer(int index, griffib.shopdroid.comms.OffersProto.Offer.Builder builderForValue) {
        result.offer_.set(index, builderForValue.build());
        return this;
      }
      public Builder addOffer(griffib.shopdroid.comms.OffersProto.Offer value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.offer_.isEmpty()) {
          result.offer_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer>();
        }
        result.offer_.add(value);
        return this;
      }
      public Builder addOffer(griffib.shopdroid.comms.OffersProto.Offer.Builder builderForValue) {
        if (result.offer_.isEmpty()) {
          result.offer_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer>();
        }
        result.offer_.add(builderForValue.build());
        return this;
      }
      public Builder addAllOffer(
          java.lang.Iterable<? extends griffib.shopdroid.comms.OffersProto.Offer> values) {
        if (result.offer_.isEmpty()) {
          result.offer_ = new java.util.ArrayList<griffib.shopdroid.comms.OffersProto.Offer>();
        }
        super.addAll(values, result.offer_);
        return this;
      }
      public Builder clearOffer() {
        result.offer_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:griffib.shopdroid.comms.Offers)
    }
    
    static {
      defaultInstance = new Offers(true);
      griffib.shopdroid.comms.OffersProto.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:griffib.shopdroid.comms.Offers)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_griffib_shopdroid_comms_Offer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_griffib_shopdroid_comms_Offer_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_griffib_shopdroid_comms_Offer_Attribute_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_griffib_shopdroid_comms_Offer_Attribute_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_griffib_shopdroid_comms_Offers_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_griffib_shopdroid_comms_Offers_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022offers_proto.proto\022\027griffib.shopdroid." +
      "comms\"\227\001\n\005Offer\022\017\n\007product\030\001 \001(\t\022\021\n\toffe" +
      "r_sum\030\002 \001(\t\022;\n\tattribute\030\003 \003(\0132(.griffib" +
      ".shopdroid.comms.Offer.Attribute\032-\n\tAttr" +
      "ibute\022\021\n\tpredicate\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"" +
      "7\n\006Offers\022-\n\005offer\030\001 \003(\0132\036.griffib.shopd" +
      "roid.comms.Offer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_griffib_shopdroid_comms_Offer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_griffib_shopdroid_comms_Offer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_griffib_shopdroid_comms_Offer_descriptor,
              new java.lang.String[] { "Product", "OfferSum", "Attribute", },
              griffib.shopdroid.comms.OffersProto.Offer.class,
              griffib.shopdroid.comms.OffersProto.Offer.Builder.class);
          internal_static_griffib_shopdroid_comms_Offer_Attribute_descriptor =
            internal_static_griffib_shopdroid_comms_Offer_descriptor.getNestedTypes().get(0);
          internal_static_griffib_shopdroid_comms_Offer_Attribute_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_griffib_shopdroid_comms_Offer_Attribute_descriptor,
              new java.lang.String[] { "Predicate", "Value", },
              griffib.shopdroid.comms.OffersProto.Offer.Attribute.class,
              griffib.shopdroid.comms.OffersProto.Offer.Attribute.Builder.class);
          internal_static_griffib_shopdroid_comms_Offers_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_griffib_shopdroid_comms_Offers_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_griffib_shopdroid_comms_Offers_descriptor,
              new java.lang.String[] { "Offer", },
              griffib.shopdroid.comms.OffersProto.Offers.class,
              griffib.shopdroid.comms.OffersProto.Offers.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
